language: minimal
jobs:
  include:
  - stage: notify-website      
    script:
    - author="$(git log -1 --pretty=format:'%an <%ce>')"
    - git clone https://SamuelMarks:$GH_TOKEN@github.com/Fantom-foundation/fantom-dev-web
      && cd fantom-dev-web
    - echo "  | [$TRAVIS_REPO_SLUG](https://github.com/$TRAVIS_REPO_SLUG) | [$TRAVIS_COMMIT_MESSAGE](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT) |" >> CHANGESLOG.md
    - git add CHANGESLOG.md
    - git commit -m "[CHANGESLOG.md] $TRAVIS_REPO_SLUG - $TRAVIS_COMMIT_MESSAGE" --author="$author"
    - git push -u origin master
env:
  global:
    secure: 't4KBuW+vZN7UJcBQsMDjIPMUiQUkpJpyHpgNqC3wb8JyCJyFaKr0OU/m71umc6ZzfBf/NL6R9vudIl5xJzHU/AYL8oTXaKyLhwO1WWPMTLAOySWDqynBQhcAakfp38YWLXY5KKrkE1UUKm+Mdy9CirGRSK1Pu3KM5vNZGFzADBfijt7AIm6/82d+ecUST6ULOemZHXrNc5P2LuR6c4iAgFqhNWrUAUuDCuU/AHbzLK2+KPqRt5AlIam+oz4VjMh9Vbzyk9szSDP520EIgb6zvLZTzCdrUV7BQCrJmbUNcPlSOjx2N63JxTF91K6HT1ZTEq4vygq48UaHn4EPBe5rz0JPWUfMtRH9IfXY2fCUe/I/BhCaxaikINtIn2yPukgo94nbfVK9Vx/uQWVoCzJ1UvqA3cctTSusxQ/VUPOCQ1HeXxGxFhdv7ERTWreerKjz7+LAqWfVZPZj0uiriSBrt0dIMiDbMwTcNMH1E3DDIPJPfRkOwMhWeOeMrcKFvtLojb1AbdCNlNCXnaujNQkGRNEHLSG2Z2c+vr+LBiHdB3GeVRR7G56ujwR5jq1tD8iXBX3wad/SD6Adj6csGnOYR2ef+R7aynacIkZ1LWhokYKm0460nfggokmRi7Nl/4yQw/dD9SsLyRqKEwp+RZmsborW6EOV6AOc68yxdtM4v50='
